/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ambari.view.k8s.requests;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


/**
 * DTO (Data Transfer Object) for the deployment request.
 * This class maps the JSON payload sent by the frontend.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class HelmDeployRequest {
    private static final ObjectMapper OM = new ObjectMapper();
    private String chart;
    private String releaseName;
    private String namespace;
    private Map<String, Object> values;
    private String serviceKey;
    private String version;
    private String secretName;
    private String repoId;
    private LinkedHashMap<String,Object> dependencies;
    private Object mounts; // accept map or list
    private transient Map<String, Object> normalizedMounts;
    private String imageGlobalRegistryProperty;
    private String deploymentMode = "DIRECT_HELM"; // DIRECT_HELM | FLUX_GITOPS
    private GitOptions git;

    // Stack-based configuration overrides (per-config/per-property)
    private Map<String, Object> stackConfigOverrides;

    // Global config management related configurations
    private List<ConfigInstantiation> configInstantiations;

    // hadoop related config maps
    private List<Map<String,Object>> requiredConfigMaps; // list of cm/secret specs

    // ranger plugin related properties
    private Map<String, Map<String,Object>> ranger;      // keyed items (security/audit/ssl/truststores)

    // endpoints (UI / external URLs etc)
    private List<Map<String,Object>> endpoints;

    // Optional security profile name
    private String securityProfile;

    // Optional TLS/autogenerated certificate configuration
    private Map<String, Object> tls;

    // Optional Kerberos keytab provisioning configuration (service-defined)
    private Map<String, Object> kerberos;

    // Optional ingress TLS upload (cert/key) to create a kubernetes.io/tls Secret ahead of deploy
    private Map<String, Object> ingressTlsUpload;

    public static class GitOptions {
        private String repoUrl;
        private String baseBranch;
        private String pathPrefix;
        private String authToken;
        private String sshKey;
        private String commitMode; // DIRECT_COMMIT or PR_MODE
        private String branch;
        private String credentialAlias;

        public String getRepoUrl() { return repoUrl; }
        public void setRepoUrl(String repoUrl) { this.repoUrl = repoUrl; }
        public String getBaseBranch() { return baseBranch; }
        public void setBaseBranch(String baseBranch) { this.baseBranch = baseBranch; }
        public String getPathPrefix() { return pathPrefix; }
        public void setPathPrefix(String pathPrefix) { this.pathPrefix = pathPrefix; }
        public String getAuthToken() { return authToken; }
        public void setAuthToken(String authToken) { this.authToken = authToken; }
        public String getSshKey() { return sshKey; }
        public void setSshKey(String sshKey) { this.sshKey = sshKey; }
        public String getCommitMode() { return commitMode; }
        public void setCommitMode(String commitMode) { this.commitMode = commitMode; }
        public String getBranch() { return branch; }
        public void setBranch(String branch) { this.branch = branch; }
        public String getCredentialAlias() { return credentialAlias; }
        public void setCredentialAlias(String credentialAlias) { this.credentialAlias = credentialAlias; }
    }

    // Getters and Setters
    public String getChart() { 
        return chart; 
    }
    
    public void setChart(String chart) { 
        this.chart = chart; 
    }
    
    public String getReleaseName() { 
        return releaseName; 
    }
    
    public void setReleaseName(String releaseName) { 
        this.releaseName = releaseName; 
    }
    
    public String getNamespace() { 
        return namespace; 
    }
    
    public void setNamespace(String namespace) { 
        this.namespace = namespace; 
    }
    
    public Map<String, Object> getValues() { 
        return values; 
    }
    
    public void setValues(Map<String, Object> values) { 
        this.values = values; 
    }

    public String getServiceKey() { 
        return serviceKey; 
    }
    
    public void setServiceKey(String serviceKey) { 
        this.serviceKey = serviceKey; 
    }

    public String getRepoId() {
        return repoId;
    }

    public void setRepoId(String repoId) {
        this.repoId = repoId;
    }

    public String getDeploymentMode() {
        return deploymentMode;
    }

    public void setDeploymentMode(String deploymentMode) {
        this.deploymentMode = deploymentMode;
    }

    public GitOptions getGit() {
        return git;
    }

    public void setGit(GitOptions git) {
        this.git = git;
    }

    public void setDependencies(LinkedHashMap<String, Object> dependencies) {
        this.dependencies = dependencies;
    }

    public LinkedHashMap<String, Object> getDependencies(){
        return this.dependencies;
    }

    public void setVersion(String version){
        this.version = version;
    }
    public String getVersion(){
        return this.version;
    }

    public void setSecretName(String secretName){
        this.secretName = secretName;
    }
    public String getSecretName(){ return this.secretName ;}

    public Map<String, Object> getMounts() {
        if (normalizedMounts != null) return normalizedMounts;
        if (mounts == null) return null;
        try {
            if (mounts instanceof Map) {
                //noinspection unchecked
                normalizedMounts = (Map<String, Object>) mounts;
                return normalizedMounts;
            }
            if (mounts instanceof List) {
                LinkedHashMap<String, Object> converted = new LinkedHashMap<>();
                int idx = 0;
                for (Object o : (List<?>) mounts) {
                    if (o instanceof Map<?, ?> m) {
                        Object k = m.get("key");
                        String key = (k != null) ? String.valueOf(k) : "mount-" + idx;
                        converted.put(key, m);
                    } else {
                        converted.put("mount-" + idx, o);
                    }
                    idx++;
                }
                normalizedMounts = converted;
                return normalizedMounts;
            }
            if (mounts instanceof String s) {
                if (s.isBlank()) return null;
                // Attempt to parse JSON string
                Object parsed = OM.readValue(s, Object.class);
                this.mounts = parsed;
                return getMounts();
            }
        } catch (Exception ignore) {
            // fall through
        }
        return null;
    }

    public String getImageGlobalRegistryProperty() { return this.imageGlobalRegistryProperty; }

    public void setImageGlobalRegistryProperty(String imageGlobalRegistryProperty) {
        this.imageGlobalRegistryProperty = imageGlobalRegistryProperty;
    };

    public Map<String, Object> getStackConfigOverrides() {
        return stackConfigOverrides;
    }

    @JsonSetter("stackConfigOverrides")
    public void setStackConfigOverrides(Object raw) {
        try {
            if (raw == null) {
                this.stackConfigOverrides = null;
            } else if (raw instanceof Map) {
                //noinspection unchecked
                this.stackConfigOverrides = (Map<String, Object>) raw;
            } else if (raw instanceof String s) {
                this.stackConfigOverrides = s.isBlank() ? null : OM.readValue(s, Map.class);
            }
        } catch (Exception ignore) {
            this.stackConfigOverrides = null;
        }
    }
    @JsonSetter("mounts")
    public void setMounts(Object mounts) { 
        this.mounts = mounts; 
        this.normalizedMounts = null;
    }

    public List<Map<String, Object>> getRequiredConfigMaps() { return requiredConfigMaps; }

    @JsonSetter("requiredConfigMaps")
    public void setRequiredConfigMaps(Object raw) {
        try {
            if (raw == null) {
                this.requiredConfigMaps = null;
            } else if (raw instanceof List) {
                //noinspection unchecked
                this.requiredConfigMaps = (List<Map<String,Object>>) raw;
            } else if (raw instanceof String s) {
                this.requiredConfigMaps = s.isBlank() ? null : OM.readValue(s, List.class);
            }
        } catch (Exception ignore) {
            this.requiredConfigMaps = null;
        }
    }

    /** Optional map of ranger items keyed by logical name. */
    public Map<String, Map<String, Object>> getRanger() { return ranger; }

    @JsonSetter("ranger")
    public void setRanger(Object raw) {
        try {
            if (raw == null) {
                this.ranger = null;
            } else if (raw instanceof Map) {
                //noinspection unchecked
                this.ranger = (Map<String, Map<String,Object>>) raw;
            } else if (raw instanceof String s) {
                this.ranger = s.isBlank() ? null : OM.readValue(s, Map.class);
            }
        } catch (Exception ignore) {
            this.ranger = null;
        }
    }

    // ---------------- endpoints ----------------

    public List<Map<String, Object>> getEndpoints() {
        return endpoints;
    }

    @JsonSetter("endpoints")
    public void setEndpoints(Object raw) {
        try {
            if (raw == null) {
                this.endpoints = null;
            } else if (raw instanceof List) {
                // expected shape: list of maps (each one endpoint descriptor)
                //noinspection unchecked
                this.endpoints = (List<Map<String,Object>>) raw;
            } else if (raw instanceof String s) {
                // tolerate JSON string (frontend might send serialized JSON)
                this.endpoints = s.isBlank() ? null : OM.readValue(s, List.class);
            } else {
                // anything else => ignore
                this.endpoints = null;
            }
        } catch (Exception ignore) {
            this.endpoints = null;
        }
    }

    // ----------------- security profile ----------------

    public String getSecurityProfile() {
        return securityProfile;
    }

    public void setSecurityProfile(String securityProfile) {
        this.securityProfile = securityProfile;
    }

    public Map<String, Object> getTls() {
        return tls;
    }

    @JsonSetter("tls")
    public void setTls(Object raw) {
        try {
            if (raw == null) {
                this.tls = null;
            } else if (raw instanceof Map) {
                //noinspection unchecked
                this.tls = (Map<String, Object>) raw;
            } else if (raw instanceof String s) {
                this.tls = s.isBlank() ? null : OM.readValue(s, Map.class);
            }
        } catch (Exception ignore) {
            this.tls = null;
        }
    }

    /**
     * Optional Kerberos keytab provisioning spec (service-defined).
     * The UI sends a map keyed by logical entry (e.g. "service") with
     * template data used by the backend to generate principals and Secrets.
     */
    public Map<String, Object> getKerberos() {
        return kerberos;
    }

    /**
     * Parse Kerberos spec from the JSON payload.
     *
     * @param raw raw object (Map or JSON string).
     */
    @JsonSetter("kerberos")
    public void setKerberos(Object raw) {
        try {
            if (raw == null) {
                this.kerberos = null;
            } else if (raw instanceof Map) {
                //noinspection unchecked
                this.kerberos = (Map<String, Object>) raw;
            } else if (raw instanceof String s) {
                this.kerberos = s.isBlank() ? null : OM.readValue(s, Map.class);
            }
        } catch (Exception ignore) {
            this.kerberos = null;
        }
    }

    /**
     * Optional Ingress TLS upload payload (cert/key to create a TLS Secret).
     * Keys expected: secretName, certPem, keyPem.
     */
    public Map<String, Object> getIngressTlsUpload() {
        return ingressTlsUpload;
    }

    @JsonSetter("ingressTlsUpload")
    public void setIngressTlsUpload(Object raw) {
        try {
            if (raw == null) {
                this.ingressTlsUpload = null;
            } else if (raw instanceof Map) {
                //noinspection unchecked
                this.ingressTlsUpload = (Map<String, Object>) raw;
            } else if (raw instanceof String s) {
                this.ingressTlsUpload = s.isBlank() ? null : OM.readValue(s, Map.class);
            }
        } catch (Exception ignore) {
            this.ingressTlsUpload = null;
        }
    }

    // ----------------- global config management --------------
    public List<ConfigInstantiation> getConfigInstantiations() {
        return configInstantiations;
    }
    public void setConfigInstantiations(List<ConfigInstantiation> configInstantiations) {
        this.configInstantiations = configInstantiations;
    }

    public static class ConfigInstantiation {
        public String profileId;      // The DB ID of the Global Config
        public String targetSecretName; // What to name the Secret in K8s
        // We don't need targetNamespace, it's the same as the Release
    }

}
