/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ambari.view.k8s.service;

import java.util.Locale;

/**
 * Renders the Airflow DAG that runs a KDPS-deployed dbt release.
 *
 * <p>The DAG does not describe how to run dbt. It asks Kubernetes to create a Job from the
 * scheduled-run template the chart already installed, then waits for it. That keeps one definition
 * of what a dbt run is — image, profile, project checkout, security material — inside the chart,
 * so a run triggered from Airflow and a run triggered by the chart's own schedule are the same run.
 * Anything else duplicates a pod spec in a second place and lets the two drift.
 *
 * <p>The output is deterministic: the same release and settings produce byte-identical text, so
 * re-publishing after an unchanged re-install leaves the repository untouched and creates no commit.
 */
public final class DbtAirflowDagService {

    private DbtAirflowDagService() {
    }

    /** File name for a release's DAG, stable across installs so a re-publish overwrites in place. */
    public static String dagFileName(String releaseName, String namespace) {
        return "kdps_dbt_" + sanitizeIdentifier(releaseName + "_" + namespace) + ".py";
    }

    /** DAG id shown in Airflow. */
    public static String dagId(String releaseName, String namespace) {
        return "kdps_dbt_" + sanitizeIdentifier(releaseName + "_" + namespace);
    }

    /**
     * Python identifiers and Airflow DAG ids allow only letters, digits and underscores; a release
     * or namespace normally contains dashes.
     */
    static String sanitizeIdentifier(String raw) {
        String v = (raw == null ? "" : raw).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_]", "_");
        v = v.replaceAll("_+", "_").replaceAll("^_|_$", "");
        return v.isEmpty() ? "release" : v;
    }

    /**
     * @param releaseName  the dbt release
     * @param namespace    where it runs
     * @param schedule     cron expression, or null/blank for a DAG that is only triggered by hand
     * @param kubeConnId   Airflow connection id pointing at the cluster, blank for in-cluster
     * @param timeoutMin   how long a run may take before the DAG gives up
     */
    public static String renderDag(String releaseName,
                                   String namespace,
                                   String schedule,
                                   String kubeConnId,
                                   int timeoutMin) {
        String id = dagId(releaseName, namespace);
        String cronJob = releaseName + "-run";
        String scheduleLiteral = (schedule == null || schedule.isBlank()) ? "None" : "\"" + schedule.trim() + "\"";
        String connLiteral = (kubeConnId == null || kubeConnId.isBlank()) ? "None" : "\"" + kubeConnId.trim() + "\"";

        return ""
            + "\"\"\"Runs the dbt transformations of the KDPS release '" + releaseName + "'.\n"
            + "\n"
            + "Generated by KDPS. Edits are overwritten the next time the release is installed.\n"
            + "\n"
            + "The work itself is defined by the release: this creates a Job from the scheduled-run\n"
            + "template that was installed alongside it, so a run started here is identical to one\n"
            + "started by the release's own schedule — same image, same profile, same project commit,\n"
            + "same security material. Nothing about how dbt runs is repeated in this file.\n"
            + "\"\"\"\n"
            + "\n"
            + "from datetime import datetime, timedelta\n"
            + "\n"
            + "from airflow import DAG\n"
            + "from airflow.providers.cncf.kubernetes.hooks.kubernetes import KubernetesHook\n"
            + "from airflow.operators.python import PythonOperator\n"
            + "\n"
            + "RELEASE = \"" + releaseName + "\"\n"
            + "NAMESPACE = \"" + namespace + "\"\n"
            + "CRON_JOB = \"" + cronJob + "\"\n"
            + "KUBE_CONN_ID = " + connLiteral + "\n"
            + "RUN_TIMEOUT = timedelta(minutes=" + Math.max(1, timeoutMin) + ")\n"
            + "\n"
            + "\n"
            + "def _clients():\n"
            + "    from kubernetes import client\n"
            + "\n"
            + "    hook = KubernetesHook(conn_id=KUBE_CONN_ID)\n"
            + "    api = hook.get_conn()\n"
            + "    return client.BatchV1Api(api.api_client), client.CoreV1Api(api.api_client)\n"
            + "\n"
            + "\n"
            + "def run_dbt(**context):\n"
            + "    \"\"\"Create one Job from the release's run template and wait for it to finish.\"\"\"\n"
            + "    import time\n"
            + "\n"
            + "    from kubernetes import client\n"
            + "\n"
            + "    batch, core = _clients()\n"
            + "    template = batch.read_namespaced_cron_job(CRON_JOB, NAMESPACE).spec.job_template\n"
            + "\n"
            + "    # One Job per Airflow run, named after it, so a retry is a new Job and the history\n"
            + "    # in Kubernetes lines up with the history in Airflow.\n"
            + "    job_name = (\"%s-%s\" % (CRON_JOB, context[\"run_id\"]))\n"
            + "    job_name = \"\".join(c if c.isalnum() else \"-\" for c in job_name.lower()).strip(\"-\")[:63].rstrip(\"-\")\n"
            + "\n"
            + "    job = client.V1Job(\n"
            + "        metadata=client.V1ObjectMeta(\n"
            + "            name=job_name,\n"
            + "            namespace=NAMESPACE,\n"
            + "            labels={\"app.kubernetes.io/instance\": RELEASE, \"kdps.clemlab.com/triggered-by\": \"airflow\"},\n"
            + "        ),\n"
            + "        spec=template.spec,\n"
            + "    )\n"
            + "    batch.create_namespaced_job(NAMESPACE, job)\n"
            + "    print(\"created job %s in %s\" % (job_name, NAMESPACE))\n"
            + "\n"
            + "    deadline = time.time() + RUN_TIMEOUT.total_seconds()\n"
            + "    while time.time() < deadline:\n"
            + "        status = batch.read_namespaced_job_status(job_name, NAMESPACE).status\n"
            + "        if status.succeeded:\n"
            + "            print(\"dbt run finished successfully\")\n"
            + "            return\n"
            + "        if status.failed:\n"
            + "            # Surface dbt's own output in the Airflow log rather than a bare exit code.\n"
            + "            pods = core.list_namespaced_pod(NAMESPACE, label_selector=\"job-name=%s\" % job_name)\n"
            + "            for pod in pods.items:\n"
            + "                try:\n"
            + "                    print(core.read_namespaced_pod_log(pod.metadata.name, NAMESPACE, container=\"dbt\"))\n"
            + "                except Exception as err:  # noqa: BLE001 - best effort, the failure below is what matters\n"
            + "                    print(\"could not read logs of %s: %s\" % (pod.metadata.name, err))\n"
            + "            raise RuntimeError(\"dbt run failed; see the pod log above\")\n"
            + "        time.sleep(10)\n"
            + "\n"
            + "    raise RuntimeError(\"dbt run did not finish within %s\" % RUN_TIMEOUT)\n"
            + "\n"
            + "\n"
            + "with DAG(\n"
            + "    dag_id=\"" + id + "\",\n"
            + "    description=\"dbt transformations for the KDPS release " + releaseName + "\",\n"
            + "    schedule=" + scheduleLiteral + ",\n"
            + "    start_date=datetime(2020, 1, 1),\n"
            + "    catchup=False,\n"
            + "    max_active_runs=1,\n"
            + "    tags=[\"kdps\", \"dbt\", RELEASE],\n"
            + "    default_args={\"retries\": 0},\n"
            + ") as dag:\n"
            + "    PythonOperator(task_id=\"dbt_run\", python_callable=run_dbt)\n";
    }
}
