package org.apache.ambari.view.k8s.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.fabric8.kubernetes.api.model.Secret;
import io.fabric8.kubernetes.client.KubernetesClient;
import org.apache.ambari.view.ViewContext;
import org.apache.ambari.view.k8s.store.K8sReleaseEntity;
import org.apache.ambari.view.k8s.store.K8sReleaseRepo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;

/**
 * Service for managing release metadata and Helm secret annotations
 */
public class ReleaseMetadataService {
    private static final Logger LOG = LoggerFactory.getLogger(ReleaseMetadataService.class);

    private final ViewContext viewContext;
    private final K8sReleaseRepo releaseRepository;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public ReleaseMetadataService(ViewContext ctx) {
        this.viewContext = ctx;
        this.releaseRepository = new K8sReleaseRepo(ctx);
    }

    public K8sReleaseEntity find(String namespace, String name) {
        return releaseRepository.findById(K8sReleaseEntity.idOf(namespace, name));
    }

    public void recordInstallOrUpgrade(
            String namespace,
            String releaseName,
            String serviceKey,           // can be null if unknown
            String chartRef,
            String repoId,               // can be null
            String version,              // can be null
            Map<String,Object> values,   // can be null
            String deploymentId          // UUID generated by UI or backend; can be null
    ) {
        String releaseId = K8sReleaseEntity.idOf(namespace, releaseName);
        K8sReleaseEntity entity = releaseRepository.findById(releaseId);
        boolean isNewEntity = (entity == null);
        
        if (entity == null) {
            entity = new K8sReleaseEntity();
            entity.setId(releaseId);
            entity.setNamespace(namespace);
            entity.setReleaseName(releaseName);
            entity.setCreatedAt(Instant.now().toString());
        }

        entity.setManagedByUi(true);
        if (serviceKey != null && !serviceKey.isBlank()) entity.setServiceKey(serviceKey);
        if (chartRef != null && !chartRef.isBlank()) entity.setChartRef(chartRef);
        if (repoId != null && !repoId.isBlank()) entity.setRepoId(repoId);
        if (version != null && !version.isBlank()) entity.setVersion(version);
        if (deploymentId != null && !deploymentId.isBlank()) entity.setDeploymentId(deploymentId);

        if (values != null) {
            try {
                entity.setValuesHash(sha256Hex(canonicalJson(values)));
            } catch (Exception ex) {
                LOG.warn("Failed to hash values for {}:{}", namespace, releaseName, ex);
            }
        }

        entity.setUpdatedAt(Instant.now().toString());

        if (isNewEntity) {
            releaseRepository.create(entity);
        } else {
            releaseRepository.update(entity);
        }
    }

    public void annotateHelmSecret(String namespace, String releaseName, Map<String,String> annotations) {
        try {
            KubernetesService kubernetesService = new KubernetesService(viewContext);
            KubernetesClient kubernetesClient = kubernetesService.getClient();
            
            if (kubernetesClient == null) {
                LOG.info("Kubernetes client not configured; skip helm secret annotation");
                return;
            }

            List<Secret> secrets = kubernetesClient.secrets()
                    .inNamespace(namespace)
                    .withLabel("owner", "helm")
                    .list().getItems();

            // Find the secret "sh.helm.release.v1.<release>.vN" with max N
            String secretPrefix = "sh.helm.release.v1." + releaseName + ".v";
            Secret latestSecret = secrets.stream()
                    .filter(secret -> secret.getMetadata() != null && secret.getMetadata().getName() != null)
                    .filter(secret -> secret.getMetadata().getName().startsWith(secretPrefix))
                    .max(Comparator.comparingInt(secret -> parseRevision(secret.getMetadata().getName(), secretPrefix)))
                    .orElse(null);

            if (latestSecret == null) {
                LOG.warn("No helm secret found for {} in namespace {}", releaseName, namespace);
                return;
            }

            final String secretName = latestSecret.getMetadata().getName();
            kubernetesClient.secrets().inNamespace(namespace).withName(secretName).edit(secret -> {
                Map<String,String> existingAnnotations = secret.getMetadata().getAnnotations();
                if (existingAnnotations == null) {
                    existingAnnotations = new HashMap<>();
                }
                existingAnnotations.putAll(annotations);
                secret.getMetadata().setAnnotations(existingAnnotations);
                return secret;
            });

            LOG.info("Annotated helm secret {} with {}", secretName, annotations);
        } catch (Exception ex) {
            LOG.warn("Failed to annotate helm secret for {}:{} -> {}", namespace, releaseName, ex.toString());
        }
    }

    private static int parseRevision(String secretName, String prefix) {
        try {
            String revisionSuffix = secretName.substring(prefix.length());
            return Integer.parseInt(revisionSuffix);
        } catch (Exception e) {
            return -1;
        }
    }

    private String canonicalJson(Map<String,Object> values) throws JsonProcessingException {
        // Stable canonical JSON (ObjectMapper's default key order is suitable for simple hashing)
        return objectMapper.writeValueAsString(values);
    }

    private static String sha256Hex(String input) {
        try {
            MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = messageDigest.digest(input.getBytes(StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();
            for (byte b : hashBytes) {
                hexString.append(String.format("%02x", b));
            }
            return hexString.toString();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
