/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ambari.view.k8s.utils;

import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamWriter;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import java.util.*;

/**
 * Deterministic Hadoop site.xml renderer.
 * - Stable sort by property name
 * - Proper XML escaping via StAX
 * - Optional <final> and <description> fields
 */
public final class HadoopSiteXml {

    private HadoopSiteXml() {}

    public static final class Entry {
        public final String name;
        public final String value;
        public final Boolean isFinal;     // null => omit <final>
        public final String description;  // null/blank => omit <description>

        public Entry(String name, String value) {
            this(name, value, null, null);
        }
        public Entry(String name, String value, Boolean isFinal, String description) {
            this.name = Objects.requireNonNull(name, "name");
            this.value = Objects.requireNonNull(value, "value");
            this.isFinal = isFinal;
            this.description = (description != null && !description.isBlank()) ? description : null;
        }
    }

    /** Convenience: build from a plain map (no <final>, no <description>). */
    public static String render(Map<String, String> properties) {
        List<Entry> entries = new ArrayList<>(properties.size());
        for (Map.Entry<String, String> e : properties.entrySet()) {
            entries.add(new Entry(e.getKey(), e.getValue()));
        }
        return render(entries, "Generated by Clemlab ("
                + OffsetDateTime.now() + ")");
    }

    /** Full control: pass explicit entries and a top-level comment. */
    public static String render(List<Entry> entries, String topComment) {
        try {
            // Sort deterministically
            entries.sort(Comparator.comparing(e -> e.name));

            StringWriter out = new StringWriter(4096);
            XMLOutputFactory f = XMLOutputFactory.newFactory();
            XMLStreamWriter xw = f.createXMLStreamWriter(out);

            xw.writeStartDocument(StandardCharsets.UTF_8.name(), "1.0");
            xw.writeCharacters("\n");
            xw.writeProcessingInstruction("xml-stylesheet", "type=\"text/xsl\" href=\"configuration.xsl\"");
            xw.writeCharacters("\n");
            xw.writeStartElement("configuration");
            xw.writeCharacters("\n");

            if (topComment != null && !topComment.isBlank()) {
                xw.writeComment(" " + topComment + " ");
                xw.writeCharacters("\n");
            }

            for (Entry e : entries) {
                xw.writeCharacters("  ");
                xw.writeStartElement("property");
                xw.writeCharacters("\n    ");
                xw.writeStartElement("name");
                xw.writeCharacters(e.name);
                xw.writeEndElement(); // name
                xw.writeCharacters("\n    ");
                xw.writeStartElement("value");
                xw.writeCharacters(e.value);
                xw.writeEndElement(); // value

                if (e.isFinal != null) {
                    xw.writeCharacters("\n    ");
                    xw.writeStartElement("final");
                    xw.writeCharacters(Boolean.TRUE.equals(e.isFinal) ? "true" : "false");
                    xw.writeEndElement(); // final
                }
                if (e.description != null) {
                    xw.writeCharacters("\n    ");
                    xw.writeStartElement("description");
                    xw.writeCharacters(e.description);
                    xw.writeEndElement(); // description
                }
                xw.writeCharacters("\n  ");
                xw.writeEndElement(); // property
                xw.writeCharacters("\n");
            }

            xw.writeEndElement(); // configuration
            xw.writeCharacters("\n");
            xw.writeEndDocument();
            xw.flush();
            xw.close();
            return out.toString();
        } catch (Exception ex) {
            throw new RuntimeException("Failed to render Hadoop site.xml", ex);
        }
    }
}